# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 6
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://github.com/TheMomentCatcher
baseurl: /
title: TheMomentCatcher
author: Slavi Galabov
description: "My name is Slavi and I am TheMomentCatcher in my channel I will always post content related to relaxation, meditation and good sleep such as: Sounds of nature - such as rain, birds, forests and waterfalls as well as a lot of content to help you in the moment of meditation and the search for the well-being of the body, soul and mind."
keywords: youtube chanel, relax viedos, nature sound videos, forest sounds, TheMomentCatcher, relaxation, meditation, good sleep, Sounds of nature
avatar: avatar.jpeg
email: azslavi@gmx.com
github: slavi-galabov # username
youtube_chanel_id: UCqbUtjR130soLFK44ooya-g?sub_confirmation=1
youtube_api_key: AIzaSyDf0IgH3w-P4BJL5fn1WgKSRJaGUBfIei4
stackoverflow: users/2352543/slavi-galabov
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-72322657-1


# needed for travis-ci build
exclude: [vendor]
